# Copyright (C) 2026 KofTwentyTwo
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: carl-prod
resources:
  - ../../base
patches:
  - target:
      kind: Ingress
      name: carl
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: carl.galaxy.direct
      - op: replace
        path: /spec/tls/0/hosts/0
        value: carl.galaxy.direct
images:
  - name: ghcr.io/koftwentytwo/carl
    newTag: UNQUALIFIED
  - name: ghcr.io/koftwentytwo/carl-migrator
    newTag: UNQUALIFIED
