-- Copyright (C) 2026 KofTwentyTwo
CREATE TABLE carl_household (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
 display_zone text NOT NULL,
 revision bigint NOT NULL DEFAULT 0
);
CREATE TABLE carl_member (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 household_id bigint NOT NULL REFERENCES carl_household(id),
 principal text NOT NULL UNIQUE,
 label text NOT NULL,
 active boolean NOT NULL DEFAULT true,
 can_manage boolean NOT NULL DEFAULT false,
 UNIQUE(id, household_id)
);
CREATE TABLE carl_permission (
 member_id bigint NOT NULL REFERENCES carl_member(id),
 domain text NOT NULL CHECK (domain IN ('BILLS','CALENDAR','VENDORS','FINANCE','TAX','SETTINGS')),
 details boolean NOT NULL DEFAULT false,
 PRIMARY KEY(member_id, domain)
);
CREATE TABLE carl_record (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 household_id bigint NOT NULL REFERENCES carl_household(id),
 owner_id bigint NOT NULL,
 domain text NOT NULL CHECK (domain IN ('BILLS','CALENDAR','VENDORS','FINANCE','TAX','SETTINGS')),
 visibility text NOT NULL CHECK (visibility IN ('PRIVATE','FAMILY')),
 title text NOT NULL CHECK (length(title) BETWEEN 1 AND 2000),
 evidence text NOT NULL CHECK (length(evidence) BETWEEN 1 AND 20000),
 effective_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(),
 revision bigint NOT NULL DEFAULT 1,
 FOREIGN KEY(owner_id, household_id) REFERENCES carl_member(id, household_id)
);
CREATE INDEX carl_record_scope ON carl_record(household_id,domain,owner_id,visibility);
CREATE TABLE carl_grant (
 record_id bigint NOT NULL REFERENCES carl_record(id),
 member_id bigint NOT NULL REFERENCES carl_member(id),
 details boolean NOT NULL DEFAULT false,
 PRIMARY KEY(record_id, member_id)
);
CREATE VIEW carl_access AS
 SELECT r.*, m.principal, m.id AS member_id,
 (p.details AND (r.owner_id=m.id OR r.visibility='FAMILY' OR coalesce(g.details,false))) AS details
 FROM carl_record r JOIN carl_member m ON m.household_id=r.household_id AND m.active
 JOIN carl_permission p ON p.member_id=m.id AND p.domain=r.domain
 LEFT JOIN carl_grant g ON g.record_id=r.id AND g.member_id=m.id
 WHERE r.owner_id=m.id OR r.visibility='FAMILY' OR g.member_id IS NOT NULL;
CREATE TABLE carl_request (
 id uuid PRIMARY KEY, member_id bigint NOT NULL REFERENCES carl_member(id), kind text NOT NULL,
 digest char(64) NOT NULL, status text NOT NULL CHECK(status IN ('PENDING','COMPLETE','PARTIAL','FAILED','UNKNOWN')),
 result_id bigint, created_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz,
 detail text NOT NULL DEFAULT ''
);
CREATE TABLE carl_import (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 household_id bigint NOT NULL REFERENCES carl_household(id),
 member_id bigint NOT NULL REFERENCES carl_member(id),
 source_name text NOT NULL, content_digest char(64) NOT NULL,
 request_id uuid NOT NULL UNIQUE REFERENCES carl_request(id),
 row_count integer NOT NULL CHECK(row_count>=0), created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(household_id,member_id,source_name,content_digest)
);
CREATE TABLE carl_vendor (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id),
 category text NOT NULL DEFAULT 'UNCLASSIFIED', contact text,
 contact_verified boolean NOT NULL DEFAULT false
);
CREATE TABLE carl_bill (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id),
 vendor_id bigint REFERENCES carl_vendor(record_id), vendor_label text NOT NULL,
 amount numeric(20,4), currency char(3) NOT NULL,
 due_date date, status text NOT NULL CHECK(status IN ('UNPAID','PAID_ASSERTED','DISPUTED','UNKNOWN')),
 payment_evidence text, import_id bigint REFERENCES carl_import(id), source_id text NOT NULL,
 CHECK(amount IS NULL OR amount>=0)
);
CREATE UNIQUE INDEX carl_bill_import_identity ON carl_bill(import_id,source_id);
CREATE TABLE carl_correction (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, record_id bigint NOT NULL REFERENCES carl_record(id),
 member_id bigint NOT NULL REFERENCES carl_member(id), reason text NOT NULL,
 before_value text NOT NULL, after_value text NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE carl_work_item (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id), vendor_id bigint NOT NULL REFERENCES carl_vendor(record_id),
 status text NOT NULL CHECK(status IN ('FAMILY_RESPONSE','VENDOR_RESPONSE','INFORMATION_NEEDED','COMPLETE')),
 assigned_member bigint REFERENCES carl_member(id), follow_up date, commitment_evidence text
);
CREATE TABLE carl_calendar_connection (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id), provider text NOT NULL CHECK(provider='CALDAV'),
 calendar_identity text NOT NULL, sync_state text NOT NULL CHECK(sync_state IN ('NOT_CONNECTED','CURRENT','FAILED','EXPIRED')),
 last_success timestamptz, last_attempt timestamptz, failure_code text
);
CREATE TABLE carl_calendar_event (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id), connection_id bigint NOT NULL REFERENCES carl_calendar_connection(record_id),
 provider_event_id text NOT NULL, occurrence_id text NOT NULL,
 start_at timestamptz, end_at timestamptz, source_zone text NOT NULL,
 all_day_start date, all_day_end_exclusive date,
 cancelled boolean NOT NULL DEFAULT false, transparent boolean NOT NULL DEFAULT false,
 free_busy_only boolean NOT NULL DEFAULT false, source_reference text,
 UNIQUE(connection_id,provider_event_id,occurrence_id),
 CHECK((start_at IS NOT NULL AND end_at>start_at AND all_day_start IS NULL AND all_day_end_exclusive IS NULL)
 OR (all_day_start IS NOT NULL AND all_day_end_exclusive>all_day_start AND start_at IS NULL AND end_at IS NULL))
);
CREATE TABLE carl_artifact (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id), request_id uuid NOT NULL UNIQUE REFERENCES carl_request(id),
 kind text NOT NULL CHECK(kind IN ('HOUSEHOLD_REPORT','BILL_REPORT','VENDOR_DRAFT','FINANCIAL_PLAN','TAX_PACKET')),
 version integer NOT NULL DEFAULT 1, period_start date, period_end date,
 facts text NOT NULL, narrative text NOT NULL, limitations text NOT NULL,
 narration_state text NOT NULL CHECK(narration_state IN ('COMPLETE','FAILED','NOT_REQUESTED')),
 source_revision bigint NOT NULL, formula_version text NOT NULL,
 intended_recipient text, status_label text NOT NULL
);
CREATE TABLE carl_artifact_source (
 artifact_id bigint NOT NULL REFERENCES carl_artifact(record_id), source_id bigint NOT NULL REFERENCES carl_record(id),
 source_revision bigint NOT NULL, PRIMARY KEY(artifact_id,source_id)
);
CREATE TABLE carl_artifact_audience (
 artifact_id bigint NOT NULL REFERENCES carl_artifact(record_id), member_id bigint NOT NULL REFERENCES carl_member(id),
 PRIMARY KEY(artifact_id,member_id)
);
CREATE TABLE carl_preference (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id), preference_key text NOT NULL, value text NOT NULL
);
CREATE TABLE carl_account (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id), kind text NOT NULL CHECK(kind IN ('CASH','CREDIT_CARD','LOAN','INVESTMENT','OTHER_ASSET')),
 institution text, currency char(3) NOT NULL, liquid boolean NOT NULL,
 ownership_share numeric(12,10) NOT NULL CHECK(ownership_share>0 AND ownership_share<=1)
);
CREATE TABLE carl_balance (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_id bigint NOT NULL REFERENCES carl_account(record_id),
 as_of date NOT NULL, amount numeric(20,4) NOT NULL,
 basis text NOT NULL CHECK(basis IN ('STATEMENT','CURRENT','ESTIMATE','HUMAN_ASSERTION')),
 evidence text NOT NULL, UNIQUE(account_id,as_of,basis)
);
CREATE TABLE carl_debt_terms (
 account_id bigint PRIMARY KEY REFERENCES carl_account(record_id),
 minimum_amount numeric(20,4), minimum_rule text, due_day integer CHECK(due_day BETWEEN 1 AND 31),
 evidence text NOT NULL, CHECK(minimum_amount IS NULL OR minimum_amount>=0)
);
CREATE TABLE carl_debt_rate (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_id bigint NOT NULL REFERENCES carl_debt_terms(account_id),
 effective_date date NOT NULL, annual_rate numeric(12,10) NOT NULL CHECK(annual_rate>=0 AND annual_rate<=5),
 monthly_fee numeric(20,4) NOT NULL DEFAULT 0 CHECK(monthly_fee>=0), evidence text NOT NULL,
 UNIQUE(account_id,effective_date)
);
CREATE TABLE carl_transaction (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id), account_id bigint NOT NULL REFERENCES carl_account(record_id),
 effective_date date NOT NULL, amount numeric(20,4) NOT NULL, currency char(3) NOT NULL,
 source_id text NOT NULL, transfer_key text,
 classification text NOT NULL CHECK(classification IN ('INCOME','EXPENSE','TRANSFER','DEBT_PRINCIPAL','DEBT_INTEREST','CAPITAL','UNCLASSIFIED')),
 category text NOT NULL, import_id bigint REFERENCES carl_import(id),
 UNIQUE(account_id,source_id)
);
CREATE TABLE carl_budget (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id), category text NOT NULL,
 period_start date NOT NULL, period_end date NOT NULL CHECK(period_end>=period_start),
 amount numeric(20,4) NOT NULL CHECK(amount>=0), currency char(3) NOT NULL
);
CREATE TABLE carl_property (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id), locality text NOT NULL,
 ownership_share numeric(12,10) NOT NULL CHECK(ownership_share>0 AND ownership_share<=1),
 asset_account_id bigint UNIQUE REFERENCES carl_account(record_id), debt_account_id bigint REFERENCES carl_account(record_id),
 legal_owner text, market_value numeric(20,4), valuation_date date, currency char(3) NOT NULL,
 acquisition_date date, acquisition_basis numeric(20,4), land_basis numeric(20,4), basis_evidence text
);
CREATE TABLE carl_rental_unit (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id), property_id bigint NOT NULL REFERENCES carl_property(record_id),
 unit_label text NOT NULL, scheduled_rent numeric(20,4), currency char(3) NOT NULL,
 lease_start date, lease_end date, occupancy text NOT NULL CHECK(occupancy IN ('OCCUPIED','VACANT','UNKNOWN'))
);
CREATE TABLE carl_property_activity (
 transaction_id bigint PRIMARY KEY REFERENCES carl_transaction(record_id), property_id bigint NOT NULL REFERENCES carl_property(record_id),
 unit_id bigint REFERENCES carl_rental_unit(record_id),
 category text NOT NULL CHECK(category IN ('RENT','OPERATING','PRINCIPAL','INTEREST','CAPITAL','RESERVE','OTHER'))
);
CREATE TABLE carl_tax_document (
 record_id bigint PRIMARY KEY REFERENCES carl_record(id), tax_year integer NOT NULL CHECK(tax_year BETWEEN 1900 AND 2200),
 jurisdiction text NOT NULL, document_kind text NOT NULL,
 property_id bigint REFERENCES carl_property(record_id), classification_state text NOT NULL CHECK(classification_state IN ('PROPOSED','CONFIRMED','UNKNOWN')),
 treatment_evidence text
);
CREATE VIEW carl_bill_view AS SELECT a.id, a.principal, a.title, a.evidence, a.created_at, a.revision,
 b.vendor_label,b.amount,b.currency,b.due_date,b.status,b.payment_evidence,b.source_id
 FROM carl_access a JOIN carl_bill b ON b.record_id=a.id WHERE a.details;
CREATE VIEW carl_vendor_view AS SELECT a.id,a.principal,a.title,a.evidence,v.category,v.contact,v.contact_verified
 FROM carl_access a JOIN carl_vendor v ON v.record_id=a.id WHERE a.details;
CREATE VIEW carl_work_view AS SELECT a.id,a.principal,a.title,a.evidence,w.vendor_id,w.status,w.assigned_member,w.follow_up,w.commitment_evidence
 FROM carl_access a JOIN carl_work_item w ON w.record_id=a.id WHERE a.details;
CREATE VIEW carl_account_view AS SELECT a.id,a.principal,a.title,a.evidence,c.kind,c.currency,c.institution,c.liquid,c.ownership_share,
 b.amount AS balance,b.as_of,b.basis
 FROM carl_access a JOIN carl_account c ON c.record_id=a.id
 LEFT JOIN LATERAL (SELECT * FROM carl_balance b WHERE b.account_id=c.record_id ORDER BY as_of DESC,id DESC LIMIT 1) b ON true WHERE a.details;
CREATE VIEW carl_property_view AS SELECT a.id,a.principal,a.title,a.evidence,p.locality,p.ownership_share,p.market_value,p.valuation_date,p.currency,p.legal_owner
 FROM carl_access a JOIN carl_property p ON p.record_id=a.id WHERE a.details;
CREATE VIEW carl_artifact_view AS SELECT a.id,a.principal,a.title,a.created_at,f.kind,f.version,f.period_start,f.period_end,f.facts,f.narrative,f.limitations,f.narration_state,f.status_label,
 EXISTS(SELECT 1 FROM carl_artifact_source s JOIN carl_record r ON r.id=s.source_id WHERE s.artifact_id=a.id AND s.source_revision<>r.revision) AS stale
 FROM carl_access a JOIN carl_artifact f ON f.record_id=a.id
 JOIN carl_artifact_audience audience ON audience.artifact_id=a.id AND audience.member_id=a.member_id
 WHERE a.details AND NOT EXISTS(SELECT 1 FROM carl_artifact_source s WHERE s.artifact_id=a.id AND NOT EXISTS
 (SELECT 1 FROM carl_access source WHERE source.id=s.source_id AND source.principal=a.principal AND source.details));
CREATE VIEW carl_calendar_view AS SELECT a.id,a.principal,
 CASE WHEN a.details AND NOT e.free_busy_only THEN a.title ELSE 'Busy' END AS title,
 CASE WHEN a.details AND NOT e.free_busy_only THEN a.evidence ELSE 'Event details restricted' END AS evidence,
 e.start_at,e.end_at,e.source_zone,e.all_day_start,e.all_day_end_exclusive,e.cancelled,e.transparent,
 c.last_success,c.sync_state
 FROM carl_access a JOIN carl_calendar_event e ON e.record_id=a.id JOIN carl_calendar_connection c ON c.record_id=e.connection_id;
CREATE TABLE carl_transaction_source (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 household_id bigint NOT NULL REFERENCES carl_household(id), external_id text NOT NULL,
 transaction_id bigint NOT NULL REFERENCES carl_transaction(record_id),
 version integer NOT NULL, payload_digest char(64) NOT NULL,
 import_id bigint NOT NULL REFERENCES carl_import(id), logical_row integer NOT NULL,
 account_label text NOT NULL, merchant text NOT NULL, category text NOT NULL,
 original_statement text NOT NULL, notes text NOT NULL, tags text NOT NULL, owner_label text NOT NULL, reviewed text NOT NULL,
 amount numeric(20,4) NOT NULL, effective_date date NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(household_id,external_id,version)
);
CREATE INDEX carl_transaction_source_identity ON carl_transaction_source(household_id,external_id,version DESC);
CREATE TABLE carl_balance_source (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id bigint NOT NULL REFERENCES carl_account(record_id), as_of date NOT NULL,
 amount numeric(20,4) NOT NULL, import_id bigint NOT NULL REFERENCES carl_import(id), logical_row integer NOT NULL,
 account_label text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,as_of,import_id)
);
CREATE VIEW carl_transaction_view AS SELECT a.id,a.principal,a.title,a.evidence,t.account_id,t.effective_date,t.amount,t.currency,t.classification,t.category,t.transfer_key,t.source_id
 FROM carl_access a JOIN carl_transaction t ON t.record_id=a.id WHERE a.details
 AND EXISTS(SELECT 1 FROM carl_access account WHERE account.id=t.account_id AND account.principal=a.principal AND account.details);
CREATE VIEW carl_budget_view AS SELECT a.id,a.principal,a.title,a.evidence,b.category,b.period_start,b.period_end,b.amount,b.currency
 FROM carl_access a JOIN carl_budget b ON b.record_id=a.id WHERE a.details;
CREATE VIEW carl_tax_view AS SELECT a.id,a.principal,a.title,a.evidence,t.tax_year,t.jurisdiction,t.document_kind,t.classification_state,t.treatment_evidence
 FROM carl_access a JOIN carl_tax_document t ON t.record_id=a.id WHERE a.details;
